name: news_alert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  path: ^1.9.0
  http: ^1.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
